config/routes.rb
Rails.application.routes.draw do

  root   'static_pages#home'
  
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :users
  
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :entries
  resources :entries do
    resources :comments
  end
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  has_many :comments
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  mount_uploader :picture, PictureUploader
  validates :content, presence: true, length: { maximum: 140 }
  validate  :picture_size
  
   private

    # Validates the size of an uploaded picture.
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: :destroy
  before_action :setEntry
  
  def create
   @entry = current_user.entry.build(entry_params)
   if @entry.save
   flash[:success] = "Entry created!"
    redirect_to root_url
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end
  
  def show
    @comments = Comment.where(entry_id: @entry).order("created_at DESC")
  end
  
  def destroy
    @entry.destroy
    flash[:success] = "Micropost deleted"
    redirect_to request.referrer || root_url
  end
  
  private
   
    def entry_params
      params.require(:entry).permit(:content, :picture)
    end
    
    def setEntry
      @entry = Entry.find(params[:id])
    end
    
    def correct_user
      @entrys = current_user.entry.find_by(id: params[:id])
      redirect_to root_url if @entrys.nil?
    end
    
end

app/helpers/entry_helper.rb
module EntryHelper
end

app/views/entries/_entry.html.erb
<li id="entry-<%= entry.id %>">
  <%= link_to gravatar_for(entry.user, size: 50), entry.user %>
  <span class="user"><%= link_to entry.user.name, entry.user %></span>
  <span style="display:block">
     <%= link_to entry.content,entry_path(entry) %>
  </span>
  <span class="content">
   
    <%= image_tag entry.picture.url if entry.picture? %>
    </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(entry.created_at) %> ago.
     <% if current_user?(entry.user) %>
      <%= link_to "delete", entry, method: :delete,
                                       data: { confirm: "You sure?" } %>
    <% end %>
  </span>
</li>

app/views/entries/show.html.erb
<div class="row">
<aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @entry.user %>
        <%= @entry.user.name %>
      </h1>
    </section>
  </aside>
<div class="col-md-8">
    
 <ol class="microposts">
  <li id="entry-<%= @entry.id %>">
  <span style="display:block">
     <%= link_to @entry.content,entry_path(@entry) %>
  </span>
  <span class="content">
    <%= image_tag @entry.picture.url if @entry.picture? %>
    </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(@entry.created_at) %> ago.
     <% if current_user?(@entry.user) %>
    <% end %>
  </span>
 </li>
 <li>
     <%= render "comments/comment" %>
 </li>
</ol>
</div>
</div>